language: go

go:
  - "1.11.x"
  - "1.12.x"

dist: trusty

env:
  - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

before_script:
  - go get golang.org/x/lint/golint

script:
  - make ci

branches:
  only:
    - master
    - gomod
